export type LearningOption = {
  title: string;
  description: string;
};

export type LearningSection = {
  slug: string;
  title: string;
  description: string;
  options: LearningOption[];
};

export const learningSectionsByWorld: Record<string, LearningSection[]> = {
  "school-help": [
    {
      slug: "math",
      title: "Math",
      description: "Learn mathematics from basic arithmetic through advanced high-school and college topics.",
      options: [
        { title: "Arithmetic", description: "Whole numbers, fractions, decimals, percentages, and everyday calculations." },
        { title: "Pre-Algebra", description: "Variables, expressions, equations, ratios, and foundations for algebra." },
        { title: "Algebra I", description: "Linear equations, functions, inequalities, systems, and graphing." },
        { title: "Geometry", description: "Shapes, proofs, angles, area, volume, similarity, and coordinate geometry." },
        { title: "Algebra II", description: "Quadratics, polynomials, exponentials, logarithms, and complex equations." },
        { title: "Trigonometry", description: "Triangles, unit circle, trigonometric functions, identities, and applications." },
        { title: "Statistics & Probability", description: "Data, distributions, probability, sampling, and statistical reasoning." },
        { title: "Pre-Calculus", description: "Functions, transformations, sequences, limits, and preparation for calculus." },
        { title: "Calculus", description: "Limits, derivatives, integrals, rates of change, and applications." },
      ],
    },
    {
      slug: "science",
      title: "Science",
      description: "Understand scientific concepts, solve problems, analyze evidence, and prepare for assessments.",
      options: [
        { title: "Biology", description: "Cells, genetics, evolution, ecology, organisms, and life processes." },
        { title: "Chemistry", description: "Atoms, bonding, reactions, stoichiometry, acids, bases, and chemical systems." },
        { title: "Physics", description: "Motion, forces, energy, waves, electricity, magnetism, and modern physics." },
        { title: "Environmental Science", description: "Ecosystems, biodiversity, climate, resources, pollution, and conservation." },
        { title: "Earth Science", description: "Geology, weather, oceans, plate tectonics, and Earth systems." },
        { title: "Anatomy & Physiology", description: "Human body systems, structures, functions, and health foundations." },
        { title: "Astronomy", description: "Planets, stars, galaxies, space, gravity, and the universe." },
        { title: "Scientific Method & Labs", description: "Hypotheses, variables, experiments, data analysis, and lab reasoning." },
      ],
    },
    {
      slug: "english-writing",
      title: "English & Writing",
      description: "Improve reading, writing, grammar, vocabulary, research, and literary analysis.",
      options: [
        { title: "Essay Writing", description: "Plan, organize, draft, revise, and strengthen academic essays." },
        { title: "Grammar", description: "Sentence structure, punctuation, usage, agreement, and common mistakes." },
        { title: "Reading Comprehension", description: "Understand main ideas, details, inference, tone, and evidence." },
        { title: "Vocabulary", description: "Build word knowledge, context clues, roots, and precise usage." },
        { title: "Literature Analysis", description: "Analyze character, theme, symbolism, conflict, tone, and structure." },
        { title: "Research Writing", description: "Find sources, organize evidence, cite correctly, and build arguments." },
        { title: "Thesis Statements", description: "Create clear, focused claims that guide strong essays." },
        { title: "Creative Writing", description: "Develop stories, characters, dialogue, description, and voice." },
      ],
    },
    {
      slug: "history-social-studies",
      title: "History & Social Studies",
      description: "Study historical events, government, economics, geography, civics, and society.",
      options: [
        { title: "U.S. History", description: "Major periods, events, people, conflicts, and changes in United States history." },
        { title: "World History", description: "Civilizations, empires, revolutions, wars, and global historical change." },
        { title: "Government", description: "Institutions, branches, constitutions, elections, rights, and public policy." },
        { title: "Civics", description: "Citizenship, rights, responsibilities, law, participation, and communities." },
        { title: "Economics", description: "Markets, scarcity, incentives, trade, inflation, unemployment, and policy." },
        { title: "Geography", description: "Regions, maps, population, resources, culture, and human-environment interaction." },
        { title: "Sociology", description: "Groups, institutions, culture, inequality, norms, and social behavior." },
        { title: "Primary Source Analysis", description: "Interpret documents, evidence, perspective, context, and historical claims." },
      ],
    },
    {
      slug: "computer-science-technology",
      title: "Computer Science & Technology",
      description: "Learn coding, computer concepts, digital systems, and technology skills for school.",
      options: [
        { title: "Computer Science Fundamentals", description: "Algorithms, logic, data, computing systems, and computational thinking." },
        { title: "HTML & CSS", description: "Build and style webpages using core web technologies." },
        { title: "JavaScript", description: "Programming basics, variables, functions, logic, arrays, and web interaction." },
        { title: "Python", description: "Learn programming through syntax, logic, functions, data, and projects." },
        { title: "AP Computer Science Principles", description: "Computing ideas, data, algorithms, networks, impact, and exam preparation." },
        { title: "AP Computer Science A", description: "Java programming, classes, arrays, algorithms, and AP-style practice." },
        { title: "Digital Literacy", description: "Files, software, internet safety, productivity tools, and responsible technology use." },
        { title: "Cybersecurity Basics", description: "Passwords, threats, privacy, networks, phishing, and digital safety." },
      ],
    },
    {
      slug: "homework-assignment-help",
      title: "Homework & Assignment Help",
      description: "Bring real schoolwork and learn how to solve it instead of only receiving an answer.",
      options: [
        { title: "Explain My Homework", description: "Break down the assignment and teach the ideas needed to complete it." },
        { title: "Teach Me This Problem", description: "Work through a difficult question one step at a time." },
        { title: "Check My Work", description: "Review your attempt, identify mistakes, and explain how to improve it." },
        { title: "Practice a Similar Problem", description: "Generate a new problem that practices the same skill." },
        { title: "Break Down Instructions", description: "Turn confusing assignment directions into clear steps." },
        { title: "Project Help", description: "Plan research, tasks, structure, and next steps for a school project." },
        { title: "Study From My Notes", description: "Turn class notes into explanations, questions, and review material." },
      ],
    },
    {
      slug: "test-quiz-exam-prep",
      title: "Test, Quiz & Exam Prep",
      description: "Prepare for assessments with targeted review, practice, explanations, and mistake correction.",
      options: [
        { title: "Prepare for a Test", description: "Build a focused study plan around the topics on your test." },
        { title: "Prepare for a Quiz", description: "Review the exact skills and concepts likely to appear on a quiz." },
        { title: "Practice Questions", description: "Generate questions and receive feedback after each response." },
        { title: "Review My Weak Areas", description: "Identify topics you struggle with and target them first." },
        { title: "Explain My Mistakes", description: "Understand why an answer was wrong and how to avoid the mistake." },
        { title: "Create a Study Guide", description: "Organize important concepts, definitions, examples, and practice." },
        { title: "Flashcard Review", description: "Use quick recall prompts for vocabulary, facts, formulas, and concepts." },
        { title: "Mock Exam", description: "Practice under test-like conditions and review performance afterward." },
      ],
    },
    {
      slug: "world-languages",
      title: "World Languages",
      description: "Practice vocabulary, grammar, reading, conversation, and school language assignments.",
      options: [
        { title: "Spanish", description: "Vocabulary, grammar, reading, writing, listening, and conversation practice." },
        { title: "French", description: "Build French language skills through explanations and guided practice." },
        { title: "German", description: "Learn vocabulary, grammar, sentence structure, and conversation." },
        { title: "Mandarin Chinese", description: "Practice vocabulary, characters, pronunciation, grammar, and comprehension." },
        { title: "Japanese", description: "Learn vocabulary, grammar, kana, reading, and conversational basics." },
        { title: "Arabic", description: "Practice vocabulary, script, grammar, reading, and conversation." },
        { title: "English Language Learning", description: "Improve English vocabulary, grammar, speaking, reading, and writing." },
        { title: "Language Test Practice", description: "Prepare for classroom language tests with targeted review." },
      ],
    },
  ],

  "brain-development": [
    {
      slug: "focus-attention",
      title: "Focus & Attention",
      description: "Train concentration, distraction control, sustained attention, and deep-work ability.",
      options: [
        { title: "Focus Training", description: "Practice staying mentally engaged with one task for longer periods." },
        { title: "Attention Control", description: "Learn to direct attention intentionally instead of reacting to every distraction." },
        { title: "Distraction Control", description: "Identify distractions and build systems that reduce interruptions." },
        { title: "Deep Work", description: "Build routines for concentrated, high-effort thinking and learning." },
        { title: "Concentration Practice", description: "Use short exercises that strengthen sustained mental effort." },
        { title: "Focus Routines", description: "Create repeatable routines that make starting and staying focused easier." },
        { title: "Digital Distraction Management", description: "Reduce interruptions from phones, apps, notifications, and browsing." },
        { title: "Task Switching Control", description: "Reduce unnecessary switching and recover focus faster when interrupted." },
      ],
    },
    {
      slug: "memory-recall",
      title: "Memory & Recall",
      description: "Strengthen how you encode, retain, retrieve, and review information.",
      options: [
        { title: "Active Recall", description: "Practice retrieving information from memory instead of rereading it." },
        { title: "Spaced Repetition", description: "Review information at increasing intervals to improve long-term retention." },
        { title: "Long-Term Memory", description: "Learn how information becomes durable and easier to retrieve later." },
        { title: "Memorization Techniques", description: "Use chunking, association, imagery, and other memory strategies." },
        { title: "Remember What I Study", description: "Build a study process focused on durable recall instead of familiarity." },
        { title: "Names & Facts Memory", description: "Practice remembering names, terms, details, and factual information." },
        { title: "Memory Palace Basics", description: "Use spatial imagery to organize and retrieve information." },
        { title: "Recall Testing", description: "Test what you actually remember and target weak spots." },
      ],
    },
    {
      slug: "reading-comprehension",
      title: "Reading & Comprehension",
      description: "Read more effectively, understand difficult material, and remember what you read.",
      options: [
        { title: "Reading Comprehension", description: "Find main ideas, supporting details, implications, and meaning." },
        { title: "Reading Retention", description: "Use active methods to remember important information after reading." },
        { title: "Difficult Text", description: "Break complicated passages into simpler ideas and relationships." },
        { title: "Reading Speed", description: "Improve efficiency while protecting understanding and retention." },
        { title: "Vocabulary in Context", description: "Infer unfamiliar words using context, roots, and surrounding ideas." },
        { title: "Summarization", description: "Identify what matters and restate it accurately in fewer words." },
        { title: "Annotation Skills", description: "Mark and question text in ways that support understanding." },
        { title: "Critical Reading", description: "Evaluate claims, evidence, assumptions, bias, and reasoning while reading." },
      ],
    },
    {
      slug: "critical-thinking-reasoning",
      title: "Critical Thinking & Reasoning",
      description: "Strengthen logic, analysis, evidence evaluation, and clear thinking.",
      options: [
        { title: "Critical Thinking", description: "Question assumptions, evaluate evidence, and form better conclusions." },
        { title: "Logical Reasoning", description: "Practice valid reasoning, relationships, deductions, and structured thought." },
        { title: "Argument Analysis", description: "Identify claims, evidence, assumptions, strengths, and weaknesses." },
        { title: "Spotting Bias", description: "Recognize cognitive bias, framing, and distorted reasoning." },
        { title: "Evidence Evaluation", description: "Judge whether information actually supports a conclusion." },
        { title: "Cause vs Correlation", description: "Distinguish relationships from true causal explanations." },
        { title: "Reasoning Practice", description: "Solve short reasoning problems and receive explanation-focused feedback." },
        { title: "Mental Models", description: "Use reusable thinking frameworks to understand complex situations." },
      ],
    },
    {
      slug: "problem-solving-decisions",
      title: "Problem Solving & Decision Making",
      description: "Learn to define problems, generate options, compare tradeoffs, and choose better actions.",
      options: [
        { title: "Problem Solving", description: "Break complex problems into smaller parts and work toward solutions." },
        { title: "Decision Making", description: "Compare options, consequences, uncertainty, and priorities." },
        { title: "Root Cause Analysis", description: "Look beyond symptoms to identify why a problem is happening." },
        { title: "Systems Thinking", description: "Understand how connected parts influence one another over time." },
        { title: "Creative Problem Solving", description: "Generate more possibilities before choosing a solution." },
        { title: "Tradeoff Analysis", description: "Compare benefits, costs, risks, and constraints across options." },
        { title: "Planning Under Uncertainty", description: "Make decisions when information is incomplete or changing." },
        { title: "Real-World Scenarios", description: "Practice decisions using realistic situations and feedback." },
      ],
    },
    {
      slug: "learning-study-systems",
      title: "Learning & Study Systems",
      description: "Build efficient systems for learning, practicing, reviewing, and improving.",
      options: [
        { title: "How to Study", description: "Use active, evidence-based study habits instead of passive review." },
        { title: "How to Take Notes", description: "Capture useful information without copying everything." },
        { title: "How to Practice", description: "Design practice that targets weaknesses and builds skill." },
        { title: "How to Learn Faster", description: "Improve learning efficiency through focus, retrieval, and feedback." },
        { title: "Study Planning", description: "Turn deadlines and goals into realistic study sessions." },
        { title: "Interleaving", description: "Mix related skills so you learn when and how to use them." },
        { title: "Feedback Loops", description: "Use mistakes and results to choose what to work on next." },
        { title: "Teach It Back", description: "Test understanding by explaining ideas in your own words." },
      ],
    },
    {
      slug: "discipline-habits",
      title: "Discipline & Habits",
      description: "Build routines, consistency, self-control, and follow-through for long-term goals.",
      options: [
        { title: "Habit Building", description: "Create repeatable behaviors using cues, routines, and rewards." },
        { title: "Consistency", description: "Keep important behaviors going even when motivation changes." },
        { title: "Self-Discipline", description: "Practice doing planned work despite discomfort or distraction." },
        { title: "Goal Setting", description: "Turn broad goals into specific targets and measurable actions." },
        { title: "Breaking Bad Habits", description: "Identify triggers and redesign routines that reinforce unwanted behavior." },
        { title: "Procrastination Control", description: "Reduce avoidance and make difficult tasks easier to start." },
        { title: "Daily Routines", description: "Build practical morning, work, study, and evening routines." },
        { title: "Progress Reflection", description: "Review what worked, what failed, and what to adjust next." },
      ],
    },
    {
      slug: "creativity-mental-flexibility",
      title: "Creativity & Mental Flexibility",
      description: "Generate ideas, shift perspectives, connect concepts, and think beyond obvious answers.",
      options: [
        { title: "Creative Thinking", description: "Practice producing varied and original ideas." },
        { title: "Brainstorming", description: "Generate options quickly before filtering or judging them." },
        { title: "Perspective Shifting", description: "Look at the same situation through multiple viewpoints." },
        { title: "Idea Connection", description: "Combine unrelated concepts to create useful new possibilities." },
        { title: "Imagination Exercises", description: "Strengthen mental simulation and possibility generation." },
        { title: "Flexible Thinking", description: "Adapt when rules, information, or conditions change." },
        { title: "Design Thinking Basics", description: "Understand people, define problems, generate ideas, and test solutions." },
        { title: "Creative Challenges", description: "Use short challenges to practice originality and adaptability." },
      ],
    },
  ],

  "general-knowledge": [
    {
      slug: "history-civilizations",
      title: "History & Civilizations",
      description: "Understand major civilizations, events, movements, conflicts, and historical change.",
      options: [
        { title: "Ancient Civilizations", description: "Mesopotamia, Egypt, Greece, Rome, early Asia, Africa, and the Americas." },
        { title: "World History", description: "Major global developments from early societies to the modern world." },
        { title: "U.S. History", description: "Colonial America, independence, expansion, conflict, reform, and modern history." },
        { title: "European History", description: "Empires, religion, revolution, industrialization, war, and integration." },
        { title: "African History", description: "Kingdoms, trade, colonization, independence, culture, and modern states." },
        { title: "Asian History", description: "China, India, Japan, Southeast Asia, empires, trade, and modern change." },
        { title: "Military History", description: "Strategy, technology, major wars, and how conflict shaped societies." },
        { title: "Modern History", description: "Industrialization, world wars, Cold War, globalization, and recent change." },
      ],
    },
    {
      slug: "science-nature",
      title: "Science & Nature",
      description: "Explore the physical universe, living systems, Earth, space, and scientific discovery.",
      options: [
        { title: "Biology", description: "Life, cells, genetics, evolution, ecology, and organisms." },
        { title: "Physics", description: "Matter, motion, energy, forces, fields, waves, and the universe." },
        { title: "Chemistry", description: "Atoms, molecules, reactions, materials, and chemical behavior." },
        { title: "Space & Astronomy", description: "Planets, stars, galaxies, black holes, cosmology, and exploration." },
        { title: "Earth Science", description: "Geology, atmosphere, oceans, climate, and Earth systems." },
        { title: "Environment", description: "Ecosystems, biodiversity, resources, pollution, conservation, and climate." },
        { title: "Human Body", description: "Anatomy, physiology, body systems, health, and biological function." },
        { title: "Scientific Breakthroughs", description: "How major discoveries changed what humans understand about nature." },
      ],
    },
    {
      slug: "technology-digital-world",
      title: "Technology & The Digital World",
      description: "Understand computers, software, AI, networks, cybersecurity, and emerging technology.",
      options: [
        { title: "How Computers Work", description: "Hardware, software, operating systems, memory, storage, and processing." },
        { title: "The Internet", description: "Networks, websites, servers, protocols, domains, and online communication." },
        { title: "Artificial Intelligence", description: "Machine learning, models, agents, capabilities, limitations, and applications." },
        { title: "Cybersecurity", description: "Threats, defense, privacy, authentication, networks, and digital safety." },
        { title: "Software", description: "How applications are designed, built, deployed, and maintained." },
        { title: "Robotics", description: "Sensors, control, automation, hardware, and intelligent machines." },
        { title: "Cloud Computing", description: "Remote infrastructure, services, storage, scaling, and modern computing." },
        { title: "Emerging Technology", description: "Explore new developments across AI, biotech, energy, computing, and more." },
      ],
    },
    {
      slug: "economics-money-business",
      title: "Economics, Money & Business",
      description: "Learn how markets, money, companies, incentives, finance, and economic systems work.",
      options: [
        { title: "Economics", description: "Scarcity, incentives, markets, trade, growth, inflation, and policy." },
        { title: "Personal Finance", description: "Budgeting, saving, banking, investing, credit, and financial planning." },
        { title: "Investing Basics", description: "Stocks, bonds, funds, risk, return, diversification, and long-term investing." },
        { title: "How Businesses Work", description: "Customers, products, operations, revenue, costs, teams, and competition." },
        { title: "Entrepreneurship", description: "Ideas, customers, business models, startups, funding, and growth." },
        { title: "Banking & Credit", description: "Banks, loans, interest, credit scores, debt, and financial institutions." },
        { title: "Taxes", description: "Why taxes exist, major tax types, filing basics, and public finance." },
        { title: "Global Trade", description: "Imports, exports, exchange rates, supply chains, and international markets." },
      ],
    },
    {
      slug: "government-law-civics",
      title: "Government, Law & Civics",
      description: "Understand institutions, legal systems, rights, public policy, and civic life.",
      options: [
        { title: "How Government Works", description: "Branches, institutions, elections, agencies, and public administration." },
        { title: "Constitutions & Rights", description: "Foundational rules, civil liberties, rights, and legal protections." },
        { title: "Law Basics", description: "Courts, legal categories, procedures, evidence, and legal reasoning." },
        { title: "Civics", description: "Citizenship, participation, responsibilities, community, and public institutions." },
        { title: "Public Policy", description: "How governments identify problems, choose policies, and measure outcomes." },
        { title: "International Relations", description: "States, diplomacy, conflict, alliances, institutions, and global cooperation." },
        { title: "Political Systems", description: "Compare democracies, monarchies, authoritarian systems, and institutions." },
        { title: "Local Government", description: "Cities, counties, services, budgets, planning, and local decision making." },
      ],
    },
    {
      slug: "geography-global-affairs",
      title: "Geography & Global Affairs",
      description: "Learn how places, populations, resources, borders, and global events connect.",
      options: [
        { title: "World Geography", description: "Countries, regions, physical features, populations, and spatial relationships." },
        { title: "Maps & Navigation", description: "Coordinates, scale, projections, direction, and reading maps." },
        { title: "Population & Migration", description: "Population patterns, cities, migration, demographics, and human movement." },
        { title: "Resources & Energy", description: "Where resources come from and how societies use and trade them." },
        { title: "Global Affairs", description: "Understand major international issues, institutions, and relationships." },
        { title: "Climate & Regions", description: "Climate zones, environments, adaptation, and regional differences." },
        { title: "Cities & Urbanization", description: "How cities grow, function, and shape economic and social life." },
        { title: "Countries of the World", description: "Learn about individual countries, cultures, geography, and institutions." },
      ],
    },
    {
      slug: "psychology-human-behavior",
      title: "Psychology & Human Behavior",
      description: "Understand thinking, emotion, behavior, personality, development, and social interaction.",
      options: [
        { title: "Psychology Basics", description: "Core ideas about behavior, thought, emotion, and scientific study." },
        { title: "Cognitive Psychology", description: "Attention, memory, perception, language, learning, and thinking." },
        { title: "Social Psychology", description: "Groups, influence, identity, relationships, and social behavior." },
        { title: "Developmental Psychology", description: "How people change from childhood through adulthood." },
        { title: "Personality", description: "Traits, individual differences, personality theories, and behavior patterns." },
        { title: "Motivation", description: "Goals, rewards, needs, habits, effort, and why people act." },
        { title: "Communication", description: "How people exchange information, interpret messages, and avoid misunderstandings." },
        { title: "Decision Psychology", description: "Biases, judgment, risk, choices, and how people make decisions." },
      ],
    },
    {
      slug: "practical-life-knowledge",
      title: "Practical Life Knowledge",
      description: "Learn useful everyday knowledge for adult life, independence, work, and decision making.",
      options: [
        { title: "Budgeting", description: "Plan income, expenses, savings, and financial priorities." },
        { title: "Credit", description: "Understand credit scores, cards, borrowing, interest, and responsible use." },
        { title: "Renting & Housing", description: "Leases, deposits, utilities, moving, maintenance, and housing basics." },
        { title: "Insurance Basics", description: "Health, auto, renters, life, deductibles, premiums, and coverage." },
        { title: "Job & Workplace Basics", description: "Applications, interviews, communication, pay, policies, and workplace behavior." },
        { title: "Time Management", description: "Prioritize responsibilities, schedule work, and manage competing demands." },
        { title: "Everyday Problem Solving", description: "Handle practical decisions, compare options, and solve common life problems." },
        { title: "Digital Safety", description: "Protect accounts, recognize scams, manage privacy, and use technology safely." },
      ],
    },
    {
      slug: "culture-arts-media",
      title: "Culture, Arts & Media",
      description: "Explore art, music, film, literature, media, culture, and creative expression.",
      options: [
        { title: "Art History", description: "Major artistic periods, movements, creators, works, and visual ideas." },
        { title: "Music", description: "Genres, theory basics, history, instruments, production, and culture." },
        { title: "Film & Cinema", description: "Storytelling, directing, editing, genres, history, and visual language." },
        { title: "Literature", description: "Genres, authors, themes, movements, and major works." },
        { title: "Media Literacy", description: "Evaluate media messages, sources, framing, advertising, and misinformation." },
        { title: "World Cultures", description: "Traditions, beliefs, language, food, customs, and cultural diversity." },
        { title: "Architecture", description: "Styles, structures, design ideas, history, and the built environment." },
        { title: "Photography", description: "Composition, light, cameras, visual storytelling, and image interpretation." },
      ],
    },
  ],

  "book-intelligence": [
    {
      slug: "learn-a-book",
      title: "Learn a Book",
      description: "Turn a book into a guided learning experience instead of only reading it once.",
      options: [
        { title: "Teach Me a Book", description: "Build a complete guided learning path around a book you choose." },
        { title: "Main Ideas", description: "Identify and explain the book's central ideas clearly." },
        { title: "Chapter by Chapter", description: "Work through the book one chapter at a time with teaching and review." },
        { title: "Important Lessons", description: "Find the most useful lessons and explain why they matter." },
        { title: "Key Concepts", description: "Break down important concepts, terms, frameworks, and relationships." },
        { title: "Author's Purpose", description: "Understand what the author is trying to accomplish and why." },
        { title: "Book Roadmap", description: "Preview the structure and create a plan for reading and learning." },
      ],
    },
    {
      slug: "deep-understanding",
      title: "Deep Understanding",
      description: "Go beyond summaries and understand difficult passages, arguments, themes, and concepts.",
      options: [
        { title: "Explain a Passage", description: "Break a difficult passage into plain language and key ideas." },
        { title: "Analyze a Chapter", description: "Examine what a chapter says, how it works, and why it matters." },
        { title: "Themes", description: "Identify recurring ideas, patterns, and deeper meaning." },
        { title: "Arguments", description: "Map claims, evidence, assumptions, and reasoning." },
        { title: "Author's Ideas", description: "Understand the author's worldview, framework, and main claims." },
        { title: "Difficult Concepts", description: "Slow down and unpack ideas that are hard to understand." },
        { title: "Context", description: "Learn the historical, cultural, intellectual, or personal context behind the text." },
        { title: "Question the Book", description: "Challenge assumptions and examine what may be incomplete or debatable." },
      ],
    },
    {
      slug: "remember-what-you-read",
      title: "Remember What You Read",
      description: "Use recall, review, and testing so important ideas stay available after you finish reading.",
      options: [
        { title: "Book Recall", description: "Retrieve the important ideas without looking back at the book." },
        { title: "Practice Questions", description: "Answer questions that test real understanding rather than recognition." },
        { title: "Flashcards", description: "Create concise prompts for concepts, definitions, people, and arguments." },
        { title: "Memory Review", description: "Review weak ideas at useful intervals to improve retention." },
        { title: "Chapter Review", description: "Test what you remember after each chapter before moving on." },
        { title: "Test My Understanding", description: "Use increasingly difficult questions to expose gaps." },
        { title: "Teach It Back", description: "Explain the book in your own words and receive feedback." },
        { title: "Spaced Book Review", description: "Build a schedule for revisiting important ideas over time." },
      ],
    },
    {
      slug: "apply-what-you-learn",
      title: "Apply What You Learn",
      description: "Turn book knowledge into decisions, skills, habits, projects, and real-world action.",
      options: [
        { title: "Apply This Book", description: "Turn the book's ideas into practical actions for your situation." },
        { title: "Real-World Examples", description: "Connect abstract ideas to realistic cases and situations." },
        { title: "Exercises", description: "Practice using the book's concepts instead of only discussing them." },
        { title: "Projects", description: "Build a project that requires applying the book's lessons." },
        { title: "Personal Application", description: "Adapt useful ideas to your goals, habits, work, or life." },
        { title: "Action Plan", description: "Convert important lessons into a sequence of concrete next steps." },
        { title: "Decision Frameworks", description: "Use the book's models to make better choices." },
        { title: "Habit Implementation", description: "Turn useful principles into repeatable behavior." },
      ],
    },
    {
      slug: "compare-books-ideas",
      title: "Compare Books & Ideas",
      description: "Connect and contrast authors, arguments, frameworks, perspectives, and subjects.",
      options: [
        { title: "Compare Two Books", description: "See where two books agree, disagree, overlap, and differ." },
        { title: "Compare Authors", description: "Contrast authors' assumptions, goals, methods, and viewpoints." },
        { title: "Connect Ideas", description: "Find useful relationships between concepts across different books." },
        { title: "Compare Arguments", description: "Evaluate which claims use stronger evidence and reasoning." },
        { title: "Different Perspectives", description: "Study the same issue through opposing or complementary viewpoints." },
        { title: "Synthesize Multiple Books", description: "Combine insights from several sources into one coherent understanding." },
        { title: "Contradictions", description: "Identify apparent conflicts and examine why they exist." },
        { title: "Shared Themes", description: "Trace common ideas across authors, genres, or time periods." },
      ],
    },
    {
      slug: "fiction-literature",
      title: "Fiction & Literature",
      description: "Study novels, stories, plays, and literature through character, theme, style, and interpretation.",
      options: [
        { title: "Character Analysis", description: "Understand motivation, development, relationships, and conflict." },
        { title: "Theme Analysis", description: "Identify deeper ideas and how the text develops them." },
        { title: "Plot & Structure", description: "Analyze how events, pacing, scenes, and structure shape the story." },
        { title: "Symbolism", description: "Interpret recurring images, objects, settings, and symbolic meaning." },
        { title: "Point of View", description: "Understand narration, perspective, reliability, and effect." },
        { title: "Literary Devices", description: "Study imagery, metaphor, irony, foreshadowing, and other techniques." },
        { title: "Historical Context", description: "Connect literature to the period and culture in which it was created." },
        { title: "Essay Preparation", description: "Build evidence-based literary analysis for assignments and exams." },
      ],
    },
    {
      slug: "nonfiction-research",
      title: "Nonfiction & Research",
      description: "Learn from textbooks, biographies, essays, research, business books, and other nonfiction.",
      options: [
        { title: "Argument Breakdown", description: "Separate claims, evidence, assumptions, and conclusions." },
        { title: "Evidence Quality", description: "Judge the strength, relevance, and limits of supporting evidence." },
        { title: "Research Paper Reading", description: "Understand abstracts, methods, results, limitations, and conclusions." },
        { title: "Biography Learning", description: "Extract events, decisions, context, and lessons from a person's life." },
        { title: "Textbook Learning", description: "Turn dense textbook material into explanations, practice, and review." },
        { title: "Business Book Learning", description: "Analyze frameworks, examples, assumptions, and practical applications." },
        { title: "History Book Learning", description: "Track evidence, chronology, interpretation, and historical argument." },
        { title: "Fact vs Interpretation", description: "Separate documented information from the author's analysis or opinion." },
      ],
    },
    {
      slug: "notes-study-guides",
      title: "Notes & Study Guides",
      description: "Turn reading into organized notes, review systems, and materials you can actually study from.",
      options: [
        { title: "Chapter Notes", description: "Create concise notes that capture important ideas without copying everything." },
        { title: "Book Study Guide", description: "Organize concepts, people, arguments, examples, and review questions." },
        { title: "Concept Map", description: "Show how major ideas connect to one another." },
        { title: "Key Quote Analysis", description: "Study important quotations and explain their meaning and relevance." },
        { title: "Vocabulary List", description: "Build a list of important terms with useful explanations." },
        { title: "One-Page Summary", description: "Compress a book or chapter into the information most worth retaining." },
        { title: "Exam Review", description: "Turn assigned reading into targeted review for a test or class discussion." },
        { title: "Discussion Questions", description: "Generate questions that require interpretation, evidence, and deeper thinking." },
      ],
    },
  ],
};

export function getLearningSections(world: string) {
  return learningSectionsByWorld[world] ?? [];
}

export function getLearningSection(world: string, sectionSlug: string) {
  return getLearningSections(world).find((section) => section.slug === sectionSlug);
}
